#!/usr/bin/env bash
# Seeds the three demo personas (alice, bob, carol) into Curity's HSQLDB BEFORE the
# server opens it. Runs as an init container in the Curity pod, using the idsvr image
# itself: the image ships a pristine, schema-complete file database at
# /opt/idsvr/var/db, plus `hsqltool` (HSQLDB SqlTool) and `crypttools` (the SHA-256-crypt
# hasher Curity verifies against). We copy the pristine DB into the emptyDir the main
# container mounts at /opt/idsvr/var/db, INSERT the rows, SHUTDOWN, exit.
#
# The rows reproduce exactly what a real "create account" + TOTP enrolment writes,
# as observed in a live db.log (Curity 11.4.0):
#   accounts    — username / email / name attributes, active=1
#   credentials — subject=username, password=$5$… (crypttools)
#   devices     — device_type=idsvr-totp, account_id + owner = the account id
#   buckets     — subject=the DEVICE id, purpose=totp_key_store, {"totp_key": <base32>}
# so the presenter's authenticator entry (from `make seed-users`) keeps working across
# every Curity restart and cluster rebuild.
#
# Inputs (env, from the curity-demo-users Secret): <USER>_PASSWORD, <USER>_TOTP_SECRET.
# Usage: curity-users-init.sh            # copy + seed (init container)
#        curity-users-init.sh --render   # print the SQL only (tests / inspection)
set -euo pipefail

SEED_SRC_DB_DIR="${SEED_SRC_DB_DIR:-/opt/idsvr/var/db}"
SEED_DST_DB_DIR="${SEED_DST_DB_DIR:-/seed}"
HSQLTOOL="${HSQLTOOL:-/opt/idsvr/bin/hsqltool}"
CRYPTTOOLS="${CRYPTTOOLS:-/opt/idsvr/bin/crypttools}"

# Persona sheet — the single copy inside the cluster. Usernames are what add-roles.js
# keys roles on; names/emails are what the web app's header pill shows. Parallel arrays:
# the container's bash is modern, but the contract test runs on macOS bash 3.2.
USERNAMES=(alice bob carol)
GIVEN=(Alice Bob Carol)
FAMILY=(Andersson Bergström Carlsson)
EMAIL_DOMAIN=demo.curity.local

die() { echo "curity-users-init: $*" >&2; exit 1; }

new_uuid() {
  if [[ -r /proc/sys/kernel/random/uuid ]]; then
    cat /proc/sys/kernel/random/uuid
  else
    uuidgen | tr '[:upper:]' '[:lower:]'
  fi
}

upper() { printf '%s' "$1" | tr '[:lower:]' '[:upper:]'; }

# Fail closed on any missing input BEFORE touching the database: a half-seeded store
# would let some personas in and silently drop others.
check_inputs() {
  local u U missing=()
  for u in "${USERNAMES[@]}"; do
    U="$(upper "$u")"
    local pw_var="${U}_PASSWORD" totp_var="${U}_TOTP_SECRET"
    [[ -n "${!pw_var:-}" ]] || missing+=("$pw_var")
    [[ -n "${!totp_var:-}" ]] || missing+=("$totp_var")
  done
  [[ ${#missing[@]} -eq 0 ]] || die "missing required env: ${missing[*]}"
}

render_sql() {
  local now i u U pw_var totp_var hash account_id credential_id device_id bucket_id
  now="$(date +%s)"
  echo "-- demo personas, generated by curity-users-init.sh"
  for i in "${!USERNAMES[@]}"; do
    u="${USERNAMES[$i]}"; U="$(upper "$u")"
    pw_var="${U}_PASSWORD"; totp_var="${U}_TOTP_SECRET"
    hash="$("$CRYPTTOOLS" --password "${!pw_var}")"
    [[ "$hash" == \$5\$* ]] || die "crypttools returned an unexpected hash for $u"
    account_id="$(new_uuid)"; credential_id="$(new_uuid)"
    device_id="$(new_uuid)"; bucket_id="$(new_uuid)"
    printf "INSERT INTO \"accounts\" VALUES('%s',NULL,'%s','%s@%s',NULL,'{\"emails\":[{\"value\":\"%s@%s\",\"primary\":true}],\"name\":{\"givenName\":\"%s\",\"familyName\":\"%s\"}}',1,%s,%s);\n" \
      "$account_id" "$u" "$u" "$EMAIL_DOMAIN" "$u" "$EMAIL_DOMAIN" "${GIVEN[$i]}" "${FAMILY[$i]}" "$now" "$now"
    printf "INSERT INTO \"credentials\" VALUES('%s',NULL,'%s','%s','{}',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);\n" \
      "$credential_id" "$u" "$hash"
    printf "INSERT INTO \"devices\" VALUES('%s','%s',NULL,'%s',NULL,'%s',NULL,'idsvr-totp','%s','{\"schemas\":[\"urn:se:curity:scim:2.0:Devices\"]}',NULL,%s,%s);\n" \
      "$(new_uuid)" "$device_id" "$account_id" "$u" "$account_id" "$now" "$now"
    printf "INSERT INTO \"buckets\" VALUES('%s','%s','totp_key_store',NULL,'{\"totp_key\":\"%s\"}',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,NULL);\n" \
      "$bucket_id" "$device_id" "${!totp_var}"
  done
  echo "SHUTDOWN;"
}

check_inputs

if [[ "${1:-}" == "--render" ]]; then
  render_sql
  exit 0
fi

[[ -f "$SEED_SRC_DB_DIR/db.script" ]] || die "no pristine HSQLDB at $SEED_SRC_DB_DIR (expected db.script)"
mkdir -p "$SEED_DST_DB_DIR"
# -R, not -a: the destination is a volume root whose times we may not set.
cp -R "$SEED_SRC_DB_DIR/." "$SEED_DST_DB_DIR/"

SQL_FILE="$(mktemp)"
trap 'rm -f "$SQL_FILE"' EXIT
render_sql > "$SQL_FILE"

echo "curity-users-init: seeding ${USERNAMES[*]} into $SEED_DST_DB_DIR/db"
"$HSQLTOOL" --inlineRc "url=jdbc:hsqldb:file:$SEED_DST_DB_DIR/db,user=sa,password=" "$SQL_FILE"
echo "curity-users-init: done"
