#!/usr/bin/env bash
# Embed the local mkcert root CA into the Curity configmap's server-truststore
# so Curity's `cimd-fetch` HTTP client trusts the gateway TLS cert when it
# dereferences each agent's CIMD client_id URL (https://*.localtest.me).
#
# The mkcert root CA is machine-specific (generated by `mkcert -install`), so
# this is an out-of-band embed step — re-run after `make certs` / on a new
# machine (sentinel-delimited injection).

set -euo pipefail

CONFIGMAP="k8s/curity/configmap.yaml"

CAROOT="$(mkcert -CAROOT 2>/dev/null || true)"
if [[ -z "$CAROOT" || ! -f "$CAROOT/rootCA.pem" ]]; then
  echo "mkcert root CA not found (run 'mkcert -install' / 'make certs' first)" >&2
  exit 1
fi

PEM="$(cat "$CAROOT/rootCA.pem")"

# Curity's server-truststore validates the declared key <size> against the cert.
# mkcert CAs are commonly 3072-bit RSA (not the 2048 default), so read it from
# the cert and declare it explicitly or ConfD rejects the config at boot.
SIZE="$(printf '%s' "$PEM" | openssl x509 -noout -text 2>/dev/null \
  | grep -oE 'Public-Key: \(([0-9]+) bit\)' | grep -oE '[0-9]+' | head -1)"
SIZE="${SIZE:-2048}"
echo "==> Embedding mkcert root CA from $CAROOT/rootCA.pem (RSA $SIZE-bit) into $CONFIGMAP"

python3 - "$CONFIGMAP" "$PEM" "$SIZE" <<'PY'
import sys, re, pathlib
path = pathlib.Path(sys.argv[1])
lines = [l for l in sys.argv[2].strip().splitlines() if l.strip()]
size = sys.argv[3]
src = path.read_text()
# The XML lives in a YAML literal block scalar indented 4 spaces. Every line must
# keep >= 4 spaces of indent or it terminates the scalar. We attach the PEM BEGIN
# marker to the <keystore> tag and indent the base64 body + END marker at exactly
# 4 spaces, so YAML strips them to column 0 — leaving a clean, unindented PEM in
# the <keystore> text value (Curity's cert parser is whitespace-sensitive).
body = "".join("    " + l + "\n" for l in lines[1:-1])
cert = (
    "<!-- BEGIN_MKCERT_CA -->\n"
    "              <server-certificate>\n"
    "                <id>mkcert-root-ca</id>\n"
    "                <size>" + size + "</size>\n"
    "                <keystore>" + lines[0] + "\n"
    + body
    + "    " + lines[-1] + "</keystore>\n"
    "              </server-certificate>\n"
    "              <!-- END_MKCERT_CA -->"
)
new, n = re.subn(
    r"<!-- BEGIN_MKCERT_CA -->.*?<!-- END_MKCERT_CA -->",
    lambda _m: cert,
    src,
    count=1,
    flags=re.DOTALL,
)
if n != 1:
    print("BEGIN_MKCERT_CA / END_MKCERT_CA sentinels not found in", path, file=sys.stderr)
    sys.exit(2)
path.write_text(new)
PY
echo "OK"
