#!/usr/bin/env bash
# `make seed-users` — publish the demo personas' credentials as the curity-demo-users
# Secret, which the Curity pod's init container (scripts/curity-users-init.sh) turns into
# accounts + TOTP enrolments before the server boots.
#
# The inputs live in a gitignored .demo-users.env. It is generated ONCE — the passwords
# default to the demo value Password1 (edit the file to change them) and each persona
# gets a random TOTP secret — and then reused verbatim on every later run. That is the
# point: add the three otpauth URIs printed below to your authenticator app once, and
# they stay valid across `make clean`, `make demo` and every Curity restart, because the
# seed re-inserts the same secrets.
set -euo pipefail

ENV_FILE="${DEMO_USERS_ENV_FILE:-.demo-users.env}"
NS="${NS_CURITY:-curity}"
USERS=(alice bob carol)
ISSUER="ai-agents-demo"

upper() { printf '%s' "$1" | tr '[:lower:]' '[:upper:]'; }

# 20 random bytes as RFC 4648 base32 (32 chars, no padding) — what authenticator apps
# and Curity's TOTP plugin both expect. node is a repo prerequisite; base32(1) is not
# on a stock macOS.
new_totp_secret() {
  node -e '
    const b = require("crypto").randomBytes(20);
    const A = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
    let bits = 0, val = 0, out = "";
    for (const x of b) { val = (val << 8) | x; bits += 8;
      while (bits >= 5) { out += A[(val >>> (bits - 5)) & 31]; bits -= 5; } }
    if (bits > 0) out += A[(val << (5 - bits)) & 31];
    process.stdout.write(out);'
}

if [[ ! -f "$ENV_FILE" ]]; then
  {
    echo "# Demo persona credentials — gitignored. Generated by 'make seed-users'."
    echo "# Passwords default to Password1; edit and re-run 'make seed-users' to change."
    echo "# Keep the TOTP secrets: they are what your authenticator app holds."
    for u in "${USERS[@]}"; do
      U="$(upper "$u")"
      echo "${U}_PASSWORD=Password1"
      echo "${U}_TOTP_SECRET=$(new_totp_secret)"
    done
  } > "$ENV_FILE"
  echo "==> Wrote $ENV_FILE (new TOTP secrets — enrol them in your authenticator once, see below)"
else
  echo "==> Reusing $ENV_FILE"
fi

kubectl create namespace "$NS" --dry-run=client -o yaml | kubectl apply -f - >/dev/null
kubectl -n "$NS" create secret generic curity-demo-users \
  --from-env-file="$ENV_FILE" \
  --dry-run=client -o yaml | kubectl apply -f -

echo ""
echo "Authenticator entries (one per persona — the same every rebuild):"
for u in "${USERS[@]}"; do
  U="$(upper "$u")"
  secret="$(sed -n "s/^${U}_TOTP_SECRET=//p" "$ENV_FILE")"
  uri="otpauth://totp/${ISSUER}:${u}?secret=${secret}&issuer=${ISSUER}&algorithm=SHA1&digits=6&period=30"
  echo "  $u  $uri"
  if command -v qrencode >/dev/null 2>&1; then qrencode -t ANSIUTF8 "$uri"; fi
done
command -v qrencode >/dev/null 2>&1 || echo "  (install qrencode to get scannable QR codes here: brew install qrencode)"
