apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: mcp-observability
spec:
  className: spire-spire
  spiffeIDTemplate: 'spiffe://{{ .TrustDomain }}/ns/{{ .PodMeta.Namespace }}/sa/{{ .PodSpec.ServiceAccountName }}'
  podSelector:
    matchLabels:
      app: mcp-observability
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: mcp
  jwtTtl: 5m
